apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - ../base/podinfo
  - ../base/flask-hello-world
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
  - path: flask-deployment.yaml
    target:
      kind: HelmRelease
