apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: podinfo
      version: '6.5.*'
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: podinfo.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
